name: Selenium WebDriver Test

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the 'main' branch

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Chrome WebDriver
        uses: actions/setup-chrome@v1

      - name: Build with Maven
        run: mvnw.cmd clean install  # Replace with your Maven build command for Windows

      - name: Run Selenium WebDriver tests
        run: mvnw.cmd test  # Replace with your Maven test command for Windows
